/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEndUI;

import Models.AttendLecture;
import Models.ReportAttendence;
import Models.Session;
import Models.Student;
import ServiceLayer.AttendLectureSession;
import ServiceLayer.SessionService;
import ServiceLayer.StudentAffairsService;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.UUID;
import javax.swing.JOptionPane;

/**
 *
 * @author Malik
 */
public class GenerateReport extends javax.swing.JFrame {

    public static String UserType = "";

    /**
     * Creates new form GenerateReport
     */
    public GenerateReport() {

        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtDiviceID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSubjectCode = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Get Total Attendence");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Below 80% Attendence");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Device ID:");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Individual Attendence");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("BACK");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Subject code");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("80% Attendence");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiviceID, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(txtSubjectCode))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiviceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            if (!txtSubjectCode.getText().isEmpty()) {
                String filereport = "D:/" + UUID.randomUUID().toString() + ".pdf";
                SessionService service = new SessionService();
                Session[] sessions = service.GetTotalSessions(txtSubjectCode.getText());
                int totalsessions = sessions.length / 2;
                AttendLectureSession attendsession = new AttendLectureSession();

                StudentAffairsService stuservice = new StudentAffairsService();
                Student[] registedStudents = stuservice.GetRegisteredStudents(txtSubjectCode.getText());
                ReportAttendence[] report = new ReportAttendence[registedStudents.length];
                int v = 0;
                for (Student tempattend : registedStudents) {

                    ReportAttendence reporttemp = new ReportAttendence();
                    reporttemp.setName(tempattend.getSName());
                    reporttemp.setStudentID(tempattend.getRegNO());
                    report[v] = reporttemp;
                    v++;
                }
                v = 0;
                for (Session tempsession : sessions) {
                    AttendLecture[] attendence = attendsession.GetAttendence(tempsession.getSessionID());
                    if (attendence != null) {
                        for (AttendLecture tempattend : attendence) {
                            for (int vk = 0; vk < report.length; vk++) {
                                if (report[vk].getStudentID().equals(tempattend.getRegNo())) {
                                    if (tempattend.getAB_P().toLowerCase().equals("present")) {
                                        report[vk].setAttendencePercentage((report[vk].getAttendencePercentage() + 1));
                                    }

                                }

                            }
                        }
                    } else {
                        System.out.println("else");
                    }

                }
                v = 0;
                for (ReportAttendence reporta : report) {
                    report[v].setAttendencePercentage(((report[v].getAttendencePercentage()) / totalsessions) * 100);
                    v++;
                }
                String pdfArray[][] = new String[report.length][3];
                for (int i = 0; i < report.length; i++) {

                    pdfArray[i][0] = report[i].getStudentID();
                    pdfArray[i][1] = report[i].getName();
                    pdfArray[i][2] = report[i].getAttendencePercentage() + " %";

                }
                createSamplePDF(new String[]{"Student ID", "Student Name", "Attendence(percentage)"}, pdfArray, filereport);
                try {

                    File file = new File(filereport);
                    Desktop.getDesktop().open(file);

                } catch (IOException exception) {

                }
                int x = 0;
            } else {
                JOptionPane.showMessageDialog(null, "Please Enter Subject code", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {

            System.out.println("exm2" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (!txtSubjectCode.getText().isEmpty()) {
                String filereport = "C:/" + UUID.randomUUID().toString() + ".pdf";
                SessionService service = new SessionService();
                Session[] sessions = service.GetTotalSessions(txtSubjectCode.getText());
                int totalsessions = sessions.length;
                AttendLectureSession attendsession = new AttendLectureSession();

                StudentAffairsService stuservice = new StudentAffairsService();
                Student[] registedStudents = stuservice.GetRegisteredStudents(txtSubjectCode.getText());
                ReportAttendence[] report = new ReportAttendence[registedStudents.length];
                int v = 0;
                for (Student tempattend : registedStudents) {

                    ReportAttendence reporttemp = new ReportAttendence();
                    reporttemp.setName(tempattend.getSName());
                    reporttemp.setStudentID(tempattend.getRegNO());
                    report[v] = reporttemp;
                    v++;
                }
                v = 0;
                for (Session tempsession : sessions) {
                    AttendLecture[] attendence = attendsession.GetAttendence(tempsession.getSessionID());
                    if (attendence != null) {
                        for (AttendLecture tempattend : attendence) {
                            for (int vk = 0; vk < report.length; vk++) {
                                if (report[vk].getStudentID().equals(tempattend.getRegNo())) {
                                    if (tempattend.getAB_P().toLowerCase().equals("present")) {
                                        report[vk].setAttendencePercentage((report[vk].getAttendencePercentage() + 1));
                                    }

                                }

                            }
                        }
                    } else {
                        System.out.println("else");
                    }

                }
                v = 0;
                for (ReportAttendence reporta : report) {
                    report[v].setAttendencePercentage(((report[v].getAttendencePercentage()) / totalsessions) * 100);
                    v++;
                }
                String pdfArray[][] = new String[report.length][3];
                for (int i = 0; i < report.length; i++) {

                    if ((Math.round(report[i].getAttendencePercentage()) / 100.0) < 80) {
                        pdfArray[i][0] = report[i].getStudentID();
                        pdfArray[i][1] = report[i].getName();
                        pdfArray[i][2] = Math.round(report[i].getAttendencePercentage()) / 100.0 + " %";

                    }

                }
                createSamplePDF(new String[]{"Student ID", "Student Name", "Attendence(percentage)"}, pdfArray, filereport);
                try {

                    File file = new File(filereport);
                    Desktop.getDesktop().open(file);

                } catch (IOException exception) {

                }
                int x = 0;
            } else {
                JOptionPane.showMessageDialog(null, "Please Enter Subject code", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {

            System.out.println("exm2" + ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            if (!txtSubjectCode.getText().isEmpty()) {
                String filereport = "D:/" + UUID.randomUUID().toString() + ".pdf";
                SessionService service = new SessionService();
                Session[] sessions = service.GetTotalSessions(txtSubjectCode.getText());
                int totalsessions = sessions.length;
                AttendLectureSession attendsession = new AttendLectureSession();

                StudentAffairsService stuservice = new StudentAffairsService();
                Student[] registedStudents = stuservice.GetRegisteredStudents(txtSubjectCode.getText());
                ReportAttendence[] report = new ReportAttendence[registedStudents.length];
                int v = 0;
                for (Student tempattend : registedStudents) {

                    ReportAttendence reporttemp = new ReportAttendence();
                    reporttemp.setName(tempattend.getSName());
                    reporttemp.setStudentID(tempattend.getRegNO());
                    report[v] = reporttemp;
                    v++;
                }
                v = 0;
                for (Session tempsession : sessions) {
                    AttendLecture[] attendence = attendsession.GetAttendence(tempsession.getSessionID());
                    if (attendence != null) {
                        for (AttendLecture tempattend : attendence) {
                            for (int vk = 0; vk < report.length; vk++) {
                                if (report[vk].getStudentID().equals(tempattend.getRegNo())) {
                                    if (tempattend.getAB_P().toLowerCase().equals("present")) {
                                        report[vk].setAttendencePercentage((report[vk].getAttendencePercentage() + 1));
                                    }

                                }

                            }
                        }
                    } else {
                        System.out.println("else");
                    }

                }
                v = 0;
                for (ReportAttendence reporta : report) {
                    report[v].setAttendencePercentage(((report[v].getAttendencePercentage()) / totalsessions) * 100);
                    v++;
                }
                String pdfArray[][] = new String[report.length][3];
                for (int i = 0; i < report.length; i++) {

                    if ((Math.round(report[i].getAttendencePercentage()) / 100.0) >= 80) {
                        pdfArray[i][0] = report[i].getStudentID();
                        pdfArray[i][1] = report[i].getName();
                        pdfArray[i][2] = Math.round(report[i].getAttendencePercentage()) / 100.0 + " %";

                    }

                }
                createSamplePDF(new String[]{"Student ID", "Student Name", "Attendence(percentage)"}, pdfArray, filereport);
                try {

                    File file = new File(filereport);
                    Desktop.getDesktop().open(file);

                } catch (IOException exception) {

                }
                int x = 0;
            } else {
                JOptionPane.showMessageDialog(null, "Please Enter Subject code", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {

            System.out.println("exm2" + ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (!txtSubjectCode.getText().isEmpty()) {
                String filereport = "C:/" + UUID.randomUUID().toString() + ".pdf";
                SessionService service = new SessionService();
                Session[] sessions = service.GetTotalSessions(txtSubjectCode.getText());
                int totalsessions = sessions.length;
                AttendLectureSession attendsession = new AttendLectureSession();

                StudentAffairsService stuservice = new StudentAffairsService();
                Student[] registedStudents = stuservice.GetRegisteredStudents(txtSubjectCode.getText());
                ReportAttendence[] report = new ReportAttendence[registedStudents.length];
                int v = 0;
                for (Student tempattend : registedStudents) {

                    ReportAttendence reporttemp = new ReportAttendence();
                    reporttemp.setName(tempattend.getSName());
                    reporttemp.setStudentID(tempattend.getRegNO());
                    report[v] = reporttemp;
                    v++;
                }
                v = 0;
                for (Session tempsession : sessions) {
                    AttendLecture[] attendence = attendsession.GetAttendence(tempsession.getSessionID());
                    if (attendence != null) {
                        for (AttendLecture tempattend : attendence) {
                            for (int vk = 0; vk < report.length; vk++) {
                                if (report[vk].getStudentID().equals(tempattend.getRegNo())) {
                                    if (tempattend.getAB_P().toLowerCase().equals("present")) {
                                        report[vk].setAttendencePercentage((report[vk].getAttendencePercentage() + 1));
                                    }

                                }

                            }
                        }
                    } else {
                        System.out.println("else");
                    }

                }
                v = 0;
                for (ReportAttendence reporta : report) {
                    report[v].setAttendencePercentage(((report[v].getAttendencePercentage()) / totalsessions) * 100);
                    v++;
                }
                String pdfArray[][] = new String[report.length][3];
                for (int i = 0; i < report.length; i++) {

                    if (report[i].getStudentID().equals(txtDiviceID.getText())) {
                        pdfArray[i][0] = report[i].getStudentID();
                        pdfArray[i][1] = report[i].getName();
                        pdfArray[i][2] = Math.round(report[i].getAttendencePercentage()) / 100.0 + " %";

                    }

                }
                createSamplePDF(new String[]{"Student ID", "Student Name", "Attendence(percentage)"}, pdfArray, filereport);
                try {

                    File file = new File(filereport);
                    Desktop.getDesktop().open(file);

                } catch (IOException exception) {

                }
                int x = 0;
            } else {
                JOptionPane.showMessageDialog(null, "Please Enter Subject code", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {

            System.out.println("exm2" + ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public static void createSamplePDF(String header[], String body[][], String filename) throws Exception {
        Document documento = new Document();
        //Create new File
        File file = new File(filename);
        file.createNewFile();
        FileOutputStream fop = new FileOutputStream(file);
        PdfWriter.getInstance(documento, fop);
        documento.open();
        //Fonts
        Font fontHeader = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);
        Font fontBody = new Font(Font.FontFamily.COURIER, 12, Font.NORMAL);
        //Table for header
        PdfPTable cabetabla = new PdfPTable(header.length);
        for (int j = 0; j < header.length; j++) {
            Phrase frase = new Phrase(header[j], fontHeader);
            PdfPCell cell = new PdfPCell(frase);
            cell.setBackgroundColor(new BaseColor(Color.lightGray.getRGB()));
            cabetabla.addCell(cell);
        }
        documento.add(cabetabla);
        //Tabla for body
        PdfPTable tabla = new PdfPTable(header.length);
        for (int i = 0; i < body.length; i++) {
            for (int j = 0; j < body[i].length; j++) {
                tabla.addCell(new Phrase(body[i][j], fontBody));
            }
        }
        documento.add(tabla);
        documento.close();
        fop.flush();
        fop.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDiviceID;
    private javax.swing.JTextField txtSubjectCode;
    // End of variables declaration//GEN-END:variables
}
